services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: accessControl
    volumes:
      - C:\temp\Codigos\postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  redis:
    image: "redis:latest"
    hostname: localhost
    ports:
      - "6379:6379"
    networks:
      - default
networks:
  default:
    driver: bridge
