
services:
  postgres:
    image: "postgres:latest"
    container_name: "accessControlDB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: accessControl
    volumes:
      - C:\temp\Codigos\postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  redis:
    image: "redis:latest"
    container_name: "accessControlRedis"
    hostname: localhost
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - redis-data:/data
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "accessControlRabbit"
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge

volumes:
  redis-data: